Repository garrettkmoody/WWU-Wash-And-Dry-Backend, pull requests merged in 2022-11, with the labels that each got.

#30 Notification system2
  app.py
  notification.py
  test_api.py
Labels: enhancement

#32 Complete Refactor
  app.py
  extensions.py
  init.py
  legacy_code.py
  models/__init__.py
  models/machine.py
  models/user.py
  requirements.txt
  routes/__init__.py
  routes/error.py
  routes/login.py
  routes/machine.py
  routes/notification.py
  routes/token.py
  routes/user.py
  test_api.py
Labels: enhancement, help wanted

#35 Added more error routes for comprehensive error handling
  routes/error.py
  routes/machine.py
  test_api.py
Labels: enhancement

#34 Updated ENDPOINTS.md to reflect current project
  docs/ENDPOINTS.md
  instance/Database.db
Labels: documentation, Ready To Be Reviewed

#40 Script to populate machine db
  instance/Database.db
  populate_db.py
Labels: Ready To Be Reviewed

#42 Validate input db
  requirements.txt
  routes/machine.py
  test_api.py
Labels: Ready To Be Reviewed

#47 Error handler tests
  models/user.py
  routes/error.py
  routes/machine.py
  routes/notification.py
  routes/user.py
  test_api.py
Labels: testing

#48 Updating Endpoint documentation
  docs/ENDPOINTS.md
Labels: documentation, Ready To Be Reviewed

#52 Second refractor of code
  .gitignore
  app/__init__.py
  app/models/__init__.py
  app/models/machine.py
  app/models/user.py
  app/routes/__init__.py
  app/routes/error.py
  app/routes/login.py
  app/routes/machine.py
  app/routes/notification.py
  app/routes/token.py
  app/routes/user.py
  extensions.py
  init.py
  routes/error.py
  routes/machine.py
  routes/user.py
  test_api.py
  tests/__init__.py
  tests/conftest.py
  tests/constants.py
  tests/test_error.py
  tests/test_login.py
  tests/test_machine_by_dorm.py
  tests/test_machine_by_floor.py
  tests/test_machine_by_floor_id.py
  tests/test_machine_by_id.py
  tests/test_notification.py
  tests/test_token.py
  tests/test_user.py
Labels: enhancement

#49 Updated documentation for setup
  README.md
Labels: documentation

#56 Creating db init function
  init.py
Labels: enhancement
